# Generated by Django 4.2.20 on 2025-06-25 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutionmatee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='phone_number',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
