# Generated by Django 5.1.6 on 2025-04-25 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutionmatee', '0003_remove_teacher_age_teacher_rate_max_teacher_rate_min'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
