# Generated by Django 5.1.6 on 2025-05-26 08:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutionmatee', '0004_teacher_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='rate_max',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='rate_min',
        ),
        migrations.AddField(
            model_name='teacher',
            name='max_rate',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)]),
        ),
        migrations.AddField(
            model_name='teacher',
            name='min_rate',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5000)]),
        ),
        migrations.AddField(
            model_name='teacher',
            name='password',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
